"use client";
import Link from "next/link";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Badge, Card, Group, Pagination, Select, SimpleGrid, Stack, Table, Text, TextInput } from "@mantine/core";
import { listAttendees, type AttendeeListResponse, type AdmissionStatus } from "@/lib/attendeeApi";
const color:Record<AdmissionStatus,string>={CONFIRMED:"teal",PAYMENT_PENDING:"yellow",RESERVED:"blue"};
export function AttendeesTable({eventId,initial}:{eventId:number;initial:AttendeeListResponse}){const[q,setQ]=useState("");const[status,setStatus]=useState<string|null>(null);const[page,setPage]=useState(1);const params=new URLSearchParams({page:String(page)});if(q.trim())params.set("q",q.trim());if(status)params.set("admission_status",status);const query=useQuery({queryKey:["event-attendees",eventId,q,status,page],queryFn:()=>listAttendees(eventId,params),initialData:q===""&&!status&&page===1?initial:undefined,placeholderData:p=>p});const data=query.data??initial;
return <Stack gap="lg"><SimpleGrid cols={{base:2,md:4}}><Summary label="Confirmed" value={data.summary.confirmed}/><Summary label="Payment pending" value={data.summary.payment_pending}/><Summary label="Reserved" value={data.summary.reserved}/><Summary label="Visible records" value={data.summary.total}/></SimpleGrid><Group align="end"><TextInput label="Search" placeholder="Name, email, ticket or buyer" value={q} onChange={e=>{setQ(e.currentTarget.value);setPage(1)}} style={{flex:1}}/><Select label="Admission status" clearable value={status} onChange={v=>{setStatus(v);setPage(1)}} data={[{value:"CONFIRMED",label:"Confirmed"},{value:"PAYMENT_PENDING",label:"Payment pending"},{value:"RESERVED",label:"Reserved"}]}/></Group><Card withBorder radius="lg" p={0}><Table.ScrollContainer minWidth={850}><Table highlightOnHover><Table.Thead><Table.Tr><Table.Th>Attendee</Table.Th><Table.Th>Ticket</Table.Th><Table.Th>Source</Table.Th><Table.Th>Admission</Table.Th><Table.Th>Check-in</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{data.attendees.map(a=><Table.Tr key={a.ticket.id}><Table.Td><Text component={Link} href={`/events/${eventId}/attendees/${a.id}`} fw={600}>{a.first_name} {a.last_name}</Text><Text size="xs" c="dimmed">{a.email}</Text></Table.Td><Table.Td>{a.ticket.name}<Text size="xs" c="dimmed">{a.ticket.reference}</Text></Table.Td><Table.Td>{a.admission_source==="CHECKOUT"?"Checkout":"Registration"}</Table.Td><Table.Td><Badge color={color[a.admission_status]} variant="light">{a.admission_status.replace("_"," ")}</Badge></Table.Td><Table.Td>{a.check_in_status==="CHECKED_IN"?<Badge color="teal">Checked in</Badge>:<Text c="dimmed">Not checked in</Text>}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>{data.attendees.length===0&&<Text ta="center" c="dimmed" py="xl">No attendees match these filters.</Text>}</Card>{data.meta.last_page>1&&<Pagination value={page} total={data.meta.last_page} onChange={setPage}/>}</Stack>}
function Summary({label,value}:{label:string;value:number}){return <Card withBorder radius="lg"><Text size="xs" c="dimmed">{label}</Text><Text fw={700} fz={24}>{value}</Text></Card>}
