"use client";

import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Badge, Button, Card, Checkbox, Container, Group, NumberInput, Select, SimpleGrid, Stack, Table, Tabs, Text, TextInput, Title } from "@mantine/core";
import { notifications } from "@mantine/notifications";
import { IconArrowLeft, IconHistory, IconPlus, IconTicket, IconTrash, IconTransferOut } from "@tabler/icons-react";
import { isValidPhoneNumber } from "libphonenumber-js";
import type { AnswerValue } from "@/lib/checkoutApi";
import type { ComplimentaryAllocation } from "@/lib/complimentaryApi";
import type { Question } from "@/lib/questionApi";
import { EditableQuestionField, isQuestionAnswered } from "@/components/EditableQuestionField";
import { PhoneInput } from "@/components/PhoneInput";

type Draft = { allocation_line_id: string; first_name: string; last_name: string; email: string; phone: string; answers: Record<number, AnswerValue> };
type HistoryOrder = { id: number; short_id: string; created_at: string; ticket_assignments: Array<{ id: number; attendee: { first_name: string; last_name: string; email: string } }>; items: Array<{ id: number; ticket_display_name: string; quantity: number }> };
const empty = (): Draft => ({ allocation_line_id: "", first_name: "", last_name: "", email: "", phone: "", answers: {} });
async function api<T>(path: string, method = "GET", body?: unknown): Promise<T> { const r = await fetch(path, { method, headers: { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); const data = await r.json(); if (!r.ok) throw new Error(data.message ?? "Something went wrong."); return data; }

export function DistributorAllocationWorkspace({ allocationId }: { allocationId: number }) {
  const cache = useQueryClient(); const key = ["distributor-allocation", allocationId];
  const detail = useQuery({ queryKey: key, queryFn: () => api<{ allocation: ComplimentaryAllocation; questions: Question[] }>(`/api/distributor/allocations/${allocationId}`), retry: false });
  const history = useQuery({ queryKey: ["distributor-allocation-history", allocationId], queryFn: () => api<{ orders: HistoryOrder[] }>(`/api/distributor/allocations/${allocationId}/history`), enabled: !!detail.data });
  const [attendees, setAttendees] = useState<Draft[]>([empty()]); const [emailTickets, setEmailTickets] = useState(true); const issuanceKey = useRef(crypto.randomUUID());
  const [returns, setReturns] = useState<Record<number, number>>({});
  const allocation = detail.data?.allocation; const questions = useMemo(() => (detail.data?.questions ?? []).sort((a, b) => a.sort_order - b.sort_order), [detail.data?.questions]);
  const refresh = () => { cache.invalidateQueries({ queryKey: key }); cache.invalidateQueries({ queryKey: ["distributor-allocation-history", allocationId] }); cache.invalidateQueries({ queryKey: ["distributor-allocations"] }); };
  const issue = useMutation({ mutationFn: () => api<{ order: { short_id: string } }>(`/api/distributor/allocations/${allocationId}/issues`, "POST", { idempotency_key: issuanceKey.current, email_tickets: emailTickets, attendees: attendees.map((a) => { const line = allocation!.lines.find((item) => item.id === Number(a.allocation_line_id))!; return { product_id: line.product_id, product_price_tier_id: line.product_price_tier_id, first_name: a.first_name.trim(), last_name: a.last_name.trim(), email: a.email.trim(), phone: a.phone || null, answers: questions.map((q) => ({ question_id: q.id, answer: a.answers[q.id] ?? "" })) }; }) }), onSuccess: ({ order }) => { notifications.show({ color: "teal", message: `Tickets issued (${order.short_id}).` }); issuanceKey.current = crypto.randomUUID(); setAttendees([empty()]); refresh(); }, onError: (e: Error) => notifications.show({ color: "red", message: e.message }) });
  const returnMutation = useMutation({ mutationFn: () => api(`/api/distributor/allocations/${allocationId}/returns`, "POST", { lines: Object.entries(returns).map(([lineId, quantity]) => { const line = allocation!.lines.find((item) => item.id === Number(lineId))!; return { product_id: line.product_id, product_price_tier_id: line.product_price_tier_id, quantity }; }).filter((line) => line.quantity > 0) }), onSuccess: () => { notifications.show({ color: "teal", message: "Unused tickets returned to the organizer pool." }); setReturns({}); refresh(); }, onError: (e: Error) => notifications.show({ color: "red", message: e.message }) });
  if (detail.isLoading) return <Container py="xl"><Text>Loading allocation…</Text></Container>;
  if (!allocation || detail.isError) return <Container py="xl"><Alert color="red">This allocation is unavailable or does not belong to your account.</Alert></Container>;
  const active = allocation.status === "ACTIVE";
  const canReturn = active || allocation.status === "SUSPENDED";
  const recipientLimit = allocation.program?.maximum_tickets_per_recipient ?? 10;
  function patch(index: number, value: Partial<Draft>) { setAttendees((rows) => rows.map((row, i) => i === index ? { ...row, ...value } : row)); }
  function submitIssue() {
    for (const [index, a] of attendees.entries()) { if (!a.allocation_line_id || !a.first_name.trim() || !a.last_name.trim() || !/^\S+@\S+\.\S+$/.test(a.email)) return notifications.show({ color: "red", message: `Complete the required details for attendee ${index + 1}.` }); if (a.phone && !isValidPhoneNumber(a.phone)) return notifications.show({ color: "red", message: `Enter a valid phone for attendee ${index + 1}.` }); for (const q of questions) if (q.is_required && !isQuestionAnswered(q, a.answers[q.id])) return notifications.show({ color: "red", message: `'${q.title}' is required for every attendee.` }); }
    const counts = new Map<string, number>(); attendees.forEach((a) => counts.set(a.email.toLowerCase(), (counts.get(a.email.toLowerCase()) ?? 0) + 1)); if (Math.max(...counts.values()) > recipientLimit) return notifications.show({ color: "red", message: "The per-recipient issuance limit was exceeded." }); issue.mutate();
  }

  return <Container size="lg" py="xl"><Stack gap="xl"><Group justify="space-between"><Stack gap={2}><Button component={Link} href="/distributor" variant="subtle" px={0} leftSection={<IconArrowLeft size={16} />}>All allocations</Button><Title order={2}>{allocation.program?.event.title}</Title><Text c="dimmed">{allocation.program?.event.organization.name}</Text></Stack><Badge color={active ? "teal" : allocation.status === "SUSPENDED" ? "yellow" : "gray"}>{allocation.status}</Badge></Group>
    {!active && <Alert color="yellow">Issuance is unavailable while this allocation is {allocation.status.toLowerCase()}.</Alert>}
    <Card withBorder><Table><Table.Thead><Table.Tr><Table.Th>Ticket</Table.Th><Table.Th>Allocated</Table.Th><Table.Th>Issued</Table.Th><Table.Th>Returned</Table.Th><Table.Th>Available</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{allocation.lines.map((line) => <Table.Tr key={line.id}><Table.Td>{line.product.title}{line.price_tier ? ` — ${line.price_tier.name}` : ""}</Table.Td><Table.Td>{line.quantity_allocated}</Table.Td><Table.Td>{line.quantity_issued}</Table.Td><Table.Td>{line.quantity_returned}</Table.Td><Table.Td>{line.quantity_available}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Card>
    <Tabs defaultValue="issue"><Tabs.List><Tabs.Tab value="issue" leftSection={<IconTicket size={15} />}>Issue tickets</Tabs.Tab><Tabs.Tab value="return" leftSection={<IconTransferOut size={15} />}>Return unused</Tabs.Tab><Tabs.Tab value="history" leftSection={<IconHistory size={15} />}>History</Tabs.Tab></Tabs.List>
      <Tabs.Panel value="issue" pt="lg"><Stack>{attendees.map((a, index) => <Card key={index} withBorder><Stack><Group justify="space-between"><Text fw={600}>Attendee {index + 1}</Text>{attendees.length > 1 && <Button size="compact-xs" variant="subtle" color="red" leftSection={<IconTrash size={13} />} onClick={() => setAttendees((rows) => rows.filter((_, i) => i !== index))}>Remove</Button>}</Group><Select required label="Ticket / option" data={allocation.lines.filter((l) => l.quantity_available > 0).map((l) => ({ value: String(l.id), label: `${l.product.title}${l.price_tier ? ` — ${l.price_tier.name}` : ""} · ${l.quantity_available} available` }))} value={a.allocation_line_id} onChange={(v) => patch(index, { allocation_line_id: v ?? "" })} /><SimpleGrid cols={{ base: 1, sm: 2 }}><TextInput required label="First name" value={a.first_name} onChange={(e) => patch(index, { first_name: e.currentTarget.value })} /><TextInput required label="Last name" value={a.last_name} onChange={(e) => patch(index, { last_name: e.currentTarget.value })} /><TextInput required type="email" label="Email" value={a.email} onChange={(e) => patch(index, { email: e.currentTarget.value })} /><PhoneInput label="Phone (optional)" value={a.phone} onChange={(phone) => patch(index, { phone })} /></SimpleGrid>{questions.map((q) => <EditableQuestionField key={q.id} question={q} value={a.answers[q.id]} onChange={(answer) => patch(index, { answers: { ...a.answers, [q.id]: answer } })} />)}</Stack></Card>)}<Group justify="space-between"><Button variant="light" leftSection={<IconPlus size={16} />} onClick={() => setAttendees((rows) => [...rows, empty()])}>Add attendee</Button><Checkbox label="Email tickets" checked={emailTickets} onChange={(e) => setEmailTickets(e.currentTarget.checked)} /></Group><Group justify="flex-end"><Button disabled={!active} loading={issue.isPending} onClick={submitIssue}>Issue {attendees.length} ticket{attendees.length === 1 ? "" : "s"}</Button></Group></Stack></Tabs.Panel>
      <Tabs.Panel value="return" pt="lg"><Card withBorder><Stack><Text>Returned tickets remain reserved for complimentary use by the organizer. They are not released for public sale.</Text>{allocation.lines.filter((line) => line.quantity_available > 0).map((line) => <Group key={line.id} justify="space-between"><Stack gap={0}><Text>{line.product.title}{line.price_tier ? ` — ${line.price_tier.name}` : ""}</Text><Text size="xs" c="dimmed">{line.quantity_available} available to return</Text></Stack><NumberInput min={0} max={line.quantity_available} value={returns[line.id] ?? 0} onChange={(v) => setReturns((current) => ({ ...current, [line.id]: Number(v) || 0 }))} /></Group>)}<Group justify="flex-end"><Button color="orange" disabled={!canReturn || !Object.values(returns).some((v) => v > 0)} loading={returnMutation.isPending} onClick={() => returnMutation.mutate()}>Return selected tickets</Button></Group></Stack></Card></Tabs.Panel>
      <Tabs.Panel value="history" pt="lg"><Stack>{history.isLoading && <Text>Loading history…</Text>}{history.data?.orders.length === 0 && <Text c="dimmed">No tickets have been issued from this allocation.</Text>}{history.data?.orders.map((order) => <Card key={order.id} withBorder><Group justify="space-between"><Stack gap={0}><Text fw={600}>{order.short_id}</Text><Text size="xs" c="dimmed">{new Date(order.created_at).toLocaleString()}</Text></Stack><Text>{order.ticket_assignments.length} ticket{order.ticket_assignments.length === 1 ? "" : "s"}</Text></Group><Text size="sm" mt="sm">{order.ticket_assignments.map((ticket) => `${ticket.attendee.first_name} ${ticket.attendee.last_name}`).join(", ")}</Text></Card>)}</Stack></Tabs.Panel>
    </Tabs></Stack></Container>;
}
