"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ActionIcon, Box, Burger, Button, Container, Divider, Drawer, Group, Menu, Stack, Text } from "@mantine/core";
import { IconChevronDown, IconSearch, IconTicket } from "@tabler/icons-react";
import { logout } from "@/lib/authApi";
import { portalLogout } from "@/lib/portalApi";
import { PublicSearchPanel } from "@/components/PublicSearchPanel";
import { ThemeToggle } from "@/components/ThemeToggle";
type NavUser = { firstName: string; lastName: string; hasOrganization: boolean } | null;
export function PublicSiteNav({ user, consumer }: { user: NavUser; consumer: { first_name: string | null; email: string } | null }) {
  const [menuOpened, setMenuOpened] = useState(false); const [searchOpened, setSearchOpened] = useState(false); const router = useRouter();
  async function signOut(kind: "consumer" | "organizer") { await (kind === "consumer" ? portalLogout() : logout()); setMenuOpened(false); router.refresh(); }
  const organizers = <Menu position="bottom-end" width={260}><Menu.Target><Button variant="subtle" rightSection={<IconChevronDown size={14}/>}>For organizers</Button></Menu.Target><Menu.Dropdown>{user ? <><Menu.Item component={Link} href={user.hasOrganization ? "/dashboard" : "/distributor"}>{user.hasOrganization ? "Organizer dashboard" : "Distributor portal"}</Menu.Item>{user.hasOrganization && <Menu.Item component={Link} href="/settings">Organizer account settings</Menu.Item>}<Menu.Item onClick={() => signOut("organizer")}>Organizer logout</Menu.Item></> : <><Menu.Item component={Link} href="/organizers/register">Create an organization</Menu.Item><Menu.Item component={Link} href="/organizers/login">Organizer login</Menu.Item></>}<Menu.Item component={Link} href="/organizers">Why Mefie for organizers</Menu.Item></Menu.Dropdown></Menu>;
  const account = consumer ? <><Button component={Link} href="/tickets" variant="subtle">My Tickets</Button><Menu><Menu.Target><Button variant="default" rightSection={<IconChevronDown size={14}/>}>{consumer.first_name || "Account"}</Button></Menu.Target><Menu.Dropdown><Menu.Label>{consumer.email}</Menu.Label><Menu.Item onClick={() => signOut("consumer")}>Log out</Menu.Item></Menu.Dropdown></Menu></> : <><Button component={Link} href="/login" variant="subtle">Log in</Button><Button component={Link} href="/register">Sign up</Button></>;
  return <><Box component="header" pos="sticky" top={0} style={{ zIndex: 100, background: "var(--mantine-color-body)", borderBottom: "1px solid var(--mantine-color-default-border)" }}><Container size="xl"><Group h={68} justify="space-between" wrap="nowrap"><Link href="/" style={{ textDecoration: "none", color: "inherit" }}><Group gap="xs" wrap="nowrap"><IconTicket size={23}/><Text fw={800}>Mefie Tickets</Text></Group></Link><Group visibleFrom="md" gap="xs" wrap="nowrap"><ActionIcon aria-label="Search events" variant="subtle" onClick={() => setSearchOpened(true)}><IconSearch/></ActionIcon><Button component={Link} href="/discover" variant="subtle">Discover events</Button>{organizers}{account}<ThemeToggle/></Group><Group hiddenFrom="md"><ActionIcon aria-label="Search events" variant="subtle" onClick={() => setSearchOpened(true)}><IconSearch/></ActionIcon><Burger opened={menuOpened} onClick={() => setMenuOpened(v => !v)} aria-label="Open navigation"/></Group></Group></Container></Box><Drawer opened={menuOpened} onClose={() => setMenuOpened(false)} title="Mefie Tickets" position="right"><Stack><ThemeToggle/><Button component={Link} href="/discover" variant="subtle">Discover events</Button>{organizers}<Divider/>{account}</Stack></Drawer><PublicSearchPanel opened={searchOpened} onClose={() => setSearchOpened(false)}/></>;
}
